version: '3'
services:
  service1:
    build: ./service1
    ports:
      - "3000:3000"  # Mapeia a porta 3000 do container para a porta 3000 do host
  service2:
    build: ./service2
    ports:
      - "5000:5000"  # Mapeia a porta 5000 do container para a porta 5000 do host
